version: '3.8'

services:
  # Este é o único serviço que você precisa.
  # Ele servirá o site (HTML, JS, CSS) e os emuladores (WASM).
  nginx:
    image: nginx:alpine
    container_name: retrocloud_nginx
    ports:
      - "8080:80"
    volumes:
      # Monta a pasta 'web' do seu PC para dentro do container
      - ./web:/usr/share/nginx/html
      # Monta a configuração customizada do Nginx
      - ./nginx_config/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
